Feature/clone field
towa-digital/towa-acf-fields pull request #6
Opened 2020-10-13 12:27 UTC by Martin-Welte

# TL;DR

- added missing clone field

## What to test and how to test

- add clone field: you will need a key from another field that needs to be cloned.

2020-10-14 10:56 UTC, SahinU88 requested changes

2020-10-14 10:56 UTC, SahinU88 commented on CHANGELOG.md
> +## unreleased
Please follow the changelog guidelines and add the appropriate header

2020-10-14 10:56 UTC, SahinU88 commented on src/Fields/CloneField.php
> +<?php
please use appropriate php-style and indent with 4 spaces, not 2.
also check the brace-style please

2022-01-10 13:23 UTC, martinWelte reviewed
changes implemented

2022-01-12 15:55 UTC, SahinU88 approved these changes

2022-01-12 15:55 UTC, merged